name: Deploy Ansible playbook to controller

on:
  push:
    branches:
      - main

jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------- Write SSH key safely and add to ssh-agent ----------
      - name: Write SSH key, fix newlines & add to ssh-agent
        env:
          SSH_KEY: ${{ secrets.devops_ansible }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          set -e
          mkdir -p ~/.ssh
          # Convert literal \n into actual newlines if secret was pasted that way
          echo "$SSH_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          # Remove CRLF line endings if any
          sed -i 's/\r$//' ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Start ssh-agent and add key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

          # Add remote host to known_hosts to avoid interactive prompt
          ssh-keyscan -H "$REMOTE_HOST" >> ~/.ssh/known_hosts || true

      # ---------- Rsync files to controller ----------
      - name: Copy repo to controller (rsync)
        run: |
          rsync -avz --delete --exclude='.git' ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/repo/

      # ---------- Run the playbook on controller ----------
      - name: Run ansible-playbook on controller via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} \
            'cd ~/repo && ansible-playbook -i inventory.ini playbook.yml'
